#!/usr/bin/env python3
"""Cut the narration excerpts out of the full voice track, join them with short
gaps, and write js/timing.js so every shot can cut on the voice's own pauses.

Excerpt boundaries were located with a pocketsphinx word-level transcript plus
ffmpeg silence detection (see PLAN.md).

usage: python3 tools/build-narration.py path/to/voice_1.mp3
"""
import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAP = 0.22         # silence between excerpts
TAIL = 3.0         # end card after the last line
FADE = 0.03

# id, start, end, in-excerpt cut points (absolute seconds in voice_1.mp3)
EXCERPTS = [
    ('founding', 0.00, 5.42, [2.26]),              # In November 1998, five young men in Shenzhen started a small software company.
    ('qq',       44.90, 47.12, []),                # The new name was just two letters: QQ.
    ('naspers',  77.10, 82.20, [78.40, 79.73]),    # In 2001, it paid about 32 million dollars for a 46.5% stake in Tencent.
    ('bestbet', 108.48, 112.10, []),               # It became one of the most successful technology investments ever made.
    ('riot',    143.70, 147.40, [145.57]),         # It paid about 400 million dollars for a 93% stake in Riot.
    ('epic',    207.88, 211.33, []),               # It invested 330 million dollars in Epic Games
    ('brands',  355.40, 363.85, [357.24, 358.92, 361.19]),  # Riot is still Riot. Epic… Supercell… other people's brands.
    ('problem', 396.96, 401.65, [398.64, 399.63, 400.60]),  # But there was a problem. Two of them… Beijing… Washington.
    ('pentagon', 576.03, 582.80, [580.64]),        # In January 2025, the Pentagon added Tencent to … the Section 1260H list.
    ('stakes',  664.48, 668.60, [666.62]),         # should Tencent be allowed to keep its stakes in Epic, Riot, and Supercell at all?
    ('ending',  900.90, 908.05, [906.17]),         # Whether it gets to keep them … It may be decided by two governments.
]


def main(src):
    out_mp3 = os.path.join(ROOT, 'assets/audio/narration-full.mp3')
    filters, labels, beats, t = [], [], {}, 0.0
    for i, (bid, a, b, cuts) in enumerate(EXCERPTS):
        d = b - a
        filters.append(f'[0:a]atrim={a}:{b},asetpts=PTS-STARTPTS,afade=t=in:d={FADE},afade=t=out:st={d - FADE:.3f}:d={FADE},'
                       f'apad=pad_dur={GAP}[s{i}]')
        labels.append(f'[s{i}]')
        beats[bid] = {'start': round(t, 3), 'dur': round(d, 3), 'pauses': [round(c - a, 3) for c in cuts]}
        t += d + GAP
    duration = round(t - GAP + TAIL, 3)
    filt = ';'.join(filters) + f';{"".join(labels)}concat=n={len(labels)}:v=0:a=1,apad=whole_dur={duration}[out]'
    subprocess.run(['ffmpeg', '-y', '-loglevel', 'error', '-i', src, '-filter_complex', filt, '-map', '[out]',
                    '-ac', '1', '-ar', '44100', '-b:a', '128k', out_mp3], check=True)
    with open(os.path.join(ROOT, 'js/timing.js'), 'w') as f:
        f.write('/* Generated by tools/build-narration.py — beat start/duration and in-beat cut points (s). */\n')
        f.write('window.TIMING = ' + json.dumps({'duration': duration, 'beats': beats}, indent=1) + ';\n')
    print(f'narration: {duration:.2f}s total, {len(EXCERPTS)} excerpts -> {out_mp3}')


if __name__ == '__main__':
    main(sys.argv[1])
