#!/usr/bin/env python3
"""Narration loudness envelope for the host's lip sync.

usage: python3 biz/tools/envelope.py narration.mp3 out.js [fps]
Writes `window.ENV = { fps, v: [...] }` — one 0..1 value per video frame (RMS, smoothed, normalised to the
95th percentile). Host.talk(t) turns it into mouth opening.
"""
import json, subprocess, sys
import numpy as np

src, out = sys.argv[1], sys.argv[2]
fps = int(sys.argv[3]) if len(sys.argv) > 3 else 30
SR = 16000
raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', src, '-ac', '1', '-ar', str(SR), '-f', 's16le', '-'], capture_output=True, check=True).stdout
x = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768
hop = SR // fps
n = len(x) // hop
rms = np.sqrt(np.array([np.mean(x[i * hop:(i + 1) * hop] ** 2) for i in range(n)]) + 1e-12)
rms = np.convolve(rms, np.ones(2) / 2, mode='same')                # tiny smoothing so the jaw doesn't chatter
v = np.clip(rms / (np.percentile(rms, 95) + 1e-9), 0, 1)
with open(out, 'w') as f:
    f.write('/* Generated by biz/tools/envelope.py — narration loudness per frame for Host.talk(). */\n')
    f.write('window.ENV = ' + json.dumps({'fps': fps, 'v': [round(float(a), 3) for a in v]}) + ';\n')
print(n, 'frames')
