/* Generated by tools/build-narration.py — beat start/duration and in-beat cut points (s). */
window.TIMING = {
 "duration": 59.89,
 "beats": {
  "founding": {
   "start": 0.0,
   "dur": 5.42,
   "pauses": [
    2.26
   ]
  },
  "qq": {
   "start": 5.64,
   "dur": 2.22,
   "pauses": []
  },
  "naspers": {
   "start": 8.08,
   "dur": 5.1,
   "pauses": [
    1.3,
    2.63
   ]
  },
  "bestbet": {
   "start": 13.4,
   "dur": 3.62,
   "pauses": []
  },
  "riot": {
   "start": 17.24,
   "dur": 3.7,
   "pauses": [
    1.87
   ]
  },
  "epic": {
   "start": 21.16,
   "dur": 3.45,
   "pauses": []
  },
  "brands": {
   "start": 24.83,
   "dur": 8.45,
   "pauses": [
    1.84,
    3.52,
    5.79
   ]
  },
  "problem": {
   "start": 33.5,
   "dur": 4.69,
   "pauses": [
    1.68,
    2.67,
    3.64
   ]
  },
  "pentagon": {
   "start": 38.41,
   "dur": 6.77,
   "pauses": [
    4.61
   ]
  },
  "stakes": {
   "start": 45.4,
   "dur": 4.12,
   "pauses": [
    2.14
   ]
  },
  "ending": {
   "start": 49.74,
   "dur": 7.15,
   "pauses": [
    5.27
   ]
  }
 }
};
